# CE - 652
## Artificial Intelligence for Autonomous Driving
## Application Assignments 
##### Week: 7
##### Instructor: Dr. Juan D. Gomez

The following function, RNNcell, implements an RNN cell exactly as illustrated in Slide 6 of the accompanying assignment deck. It faithfully replicates the computational structure depicted in the figure:



In [6]:
import numpy as np

# Define activation functions
def tanh(x):
    return np.tanh(x)

def softmax(x):
    exp_x = np.exp(x - np.max(x))  # For numerical stability
    return exp_x / exp_x.sum(axis=0, keepdims=True)

# Define the RNN Cell function
def RNNcell(x_t, a_prev):
    """
    Implements a single RNN cell computation with hardwired random weights.
    
    Args:
    x_t -- Input vector at time step t.
    a_prev -- Hidden state from the previous time step.
    
    Returns:
    a_t -- Current hidden state.
    y_t -- Output vector.
    """
    # Define dimensions
    input_size = 10  # Size of input vector x_t
    hidden_size = 4  # Size of hidden state a_t
    output_size = 10  # Size of output vector y_t
    
    # Initialize random weight matrices and biases (hardwired inside function)
    np.random.seed(42)  # For reproducibility
    W_ax = np.random.randn(hidden_size, input_size)
    W_aa = np.random.randn(hidden_size, hidden_size)
    W_ya = np.random.randn(output_size, hidden_size)
    b_a = np.random.randn(hidden_size, 1)
    b_y = np.random.randn(output_size, 1)
    
    # Compute the activation state
    a_t = tanh(np.dot(W_ax, x_t) + np.dot(W_aa, a_prev) + b_a)

    # Compute the output
    y_t = softmax(np.dot(W_ya, a_t) + b_y)
    
    return a_t, y_t

# Dummy example with arbitrary sizes
x_t = np.random.randn(10, 1)  # Random input
a_prev = np.zeros((4, 1))  # Initial hidden state

# Run the RNN cell
a_t, y_t = RNNcell(x_t, a_prev)

# Print outputs
print("Hidden State a_t:\n", a_t)
print("\nOutput y_t:\n", y_t)

Hidden State a_t:
 [[ 0.84508469]
 [-0.33334826]
 [ 0.37943232]
 [-0.99748304]]

Output y_t:
 [[0.00174899]
 [0.03111411]
 [0.00988929]
 [0.00575051]
 [0.00246197]
 [0.41265576]
 [0.44017487]
 [0.02233032]
 [0.0084768 ]
 [0.06539737]]


Please note that both the weight matrices (𝑊) and biases (𝑏) are hardcoded within the function using randomly initialized values. They have not been fine-tuned through training or optimized via backpropagation. This simplification is intentional, as this is merely a dummy exercise designed for illustrative purposes.

The hidden state has an arbitrary size of 4, while both the input (𝑥_𝑡) and output (𝑦_𝑡) word embeddings have a size of 10, indicating that this is the chosen embedding dimension. It is important to highlight that an RNN processes and outputs word embeddings rather than raw words.

Additionally, both the initial hidden state (a_prev) and the input word embedding are randomly generated, reinforcing that this is a conceptual demonstration rather than a practical application.

#### Excercise:

Please create a code that implements a many-to-many RNN architecture, where the output word at each time step serves as the input for the next step. This setup requires only the initial hidden state and the first input word to begin the sequence. Ensure that the code displays both the hidden state and the output word at every step and iterates for five time steps.

In [10]:
# Your code here

Many-to-Many RNN Execution:
Time Step 1:
Hidden State a_t:
 [[ 0.96618594]
 [-0.99998186]
 [-0.99999935]
 [-0.87372742]]
Output y_t:
 [[0.00199904]
 [0.18996277]
 [0.00796147]
 [0.00977976]
 [0.05113174]
 [0.50536737]
 [0.05944587]
 [0.01201105]
 [0.00802316]
 [0.15431777]] 

Time Step 2:
Hidden State a_t:
 [[ 0.85230509]
 [-0.93166325]
 [ 0.9621155 ]
 [-0.99841915]]
Output y_t:
 [[1.66937623e-03]
 [1.19905021e-02]
 [2.78797483e-03]
 [6.88522679e-03]
 [1.38021694e-04]
 [3.43719047e-01]
 [5.53301496e-01]
 [3.36412152e-02]
 [4.32505290e-03]
 [4.15420866e-02]] 

Time Step 3:
Hidden State a_t:
 [[ 0.94745281]
 [-0.99010336]
 [ 0.96582368]
 [-0.93192499]]
Output y_t:
 [[1.81978511e-03]
 [1.15614973e-02]
 [3.22773240e-03]
 [8.90888884e-03]
 [1.42515758e-04]
 [3.35529766e-01]
 [5.59532494e-01]
 [3.57072608e-02]
 [4.62161347e-03]
 [3.89484466e-02]] 

Time Step 4:
Hidden State a_t:
 [[ 0.95280597]
 [-0.9907017 ]
 [ 0.97204556]
 [-0.9358972 ]]
Output y_t:
 [[1.79341691e-03]
 [1.14114833e-02]
 [3